Repository hashicorp/hcp-terraform-operator, pull requests merged in 2023-04, with the labels that each got.

#121 🤖 Update GH Docker security scanner workflow
  .github/pr-labeler.yml
  .github/workflows/docker-image-security-scan.yml
Labels: size/S, github_actions

#133 🤖 Update dependabot schedule
  .github/dependabot.yml
Labels: size/XS

#122 🌱 Bump controller-tools from 0.11.1 to 0.11.3
  Makefile
Labels: dependencies, size/XS

#125 🤖 Add a new GHA to run E2E tests on a Kubernetes cluster
  .github/workflows/helm-end-to-end-tfc.yaml
  .github/workflows/helm-end-to-end-tfe.yaml
Labels: size/L

#140 🤖 Onboard CRT
  .github/workflows/build.yml
  .github/workflows/docker-image-security-scan.yml
  .github/workflows/helm-end-to-end-tfc.yaml
  .github/workflows/helm-end-to-end-tfe.yaml
  .release/ci.hcl
  .release/release-metadata.hcl
  .release/security-scan.hcl
  Dockerfile
  version/VERSION
Labels: size/XL

#143 🐛 Fix `ENTRYPOINT` and `COPY` layers in the Dockerfile
  Dockerfile
Labels: size/XS

#148 Add Docker pull badge
  README.md
Labels: documentation, size/XS

#150 v2.0.0-beta5
  CHANGELOG.md
  README.md
  charts/terraform-cloud-operator/Chart.yaml
Labels: documentation, size/XS, helm-chart

#152 Remove note from Agent Pools docs
  docs/agentpool.md
Labels: documentation, size/XS

#151 Update version and chart image tag
  charts/terraform-cloud-operator/values.yaml
  version/VERSION
Labels: size/XS, helm-chart
