Repository hashicorp/hcp-terraform-operator, pull requests merged in 2023-06, with the labels that each got.

#186 ✨ Make changes to simplify migration from v1
  CHANGELOG.md
  api/v1alpha2/workspace_types.go
  charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml
  config/crd/bases/app.terraform.io_workspaces.yaml
  controllers/consts.go
  controllers/workspace_controller.go
  docs/migration/crds/workspaces_patch_a.yaml
  docs/migration/crds/workspaces_patch_b.yaml
Labels: crd, helm-chart, api, golang, size/XL, controller

#184 Bump all GitHub Actions and pin; avoid deprecated Node 12
  .github/workflows/api-tests.yaml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-image-security-scan.yml
  .github/workflows/end-to-end-tfc.yaml
  .github/workflows/end-to-end-tfe.yaml
  .github/workflows/helm-end-to-end-tfc.yaml
  .github/workflows/helm-end-to-end-tfe.yaml
  .github/workflows/tag-release.yaml
Labels: size/XS

#200 Release/v2.0.0 beta6
  CHANGELOG.md
  charts/terraform-cloud-operator/Chart.yaml
  charts/terraform-cloud-operator/values.yaml
  version/VERSION
Labels: size/XS, helm-chart, release

#202 📖 Update the Releasing guide
  CHANGELOG.md
  README.md
  RELEASING.md
  scripts/release-date.sh
Labels: documentation, size/S

#203 🤖 Update GHA workflow `build`
  .github/workflows/build.yml
  CHANGELOG.md
Labels: size/XS
