Repository hashicorp/hcp-terraform-operator, pull requests merged in 2023-05, with the labels that each got.

#147 🌱 Bump Kustomize and Envtest dependencies
  Makefile
  charts/terraform-cloud-operator/crds/app.terraform.io_agentpools.yaml
  charts/terraform-cloud-operator/crds/app.terraform.io_modules.yaml
  charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml
  config/crd/bases/app.terraform.io_agentpools.yaml
  config/crd/bases/app.terraform.io_modules.yaml
  config/crd/bases/app.terraform.io_workspaces.yaml
Labels: size/XS, crd, helm-chart

#167 🤖 Update DependaBot config
  .github/dependabot.yml
Labels: size/XS

#168 🤖 Update pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: size/XS

#173 Add Helm chart value to configure custom CA certificates
  charts/terraform-cloud-operator/templates/ca_secret.yaml
  charts/terraform-cloud-operator/templates/deployment.yaml
  charts/terraform-cloud-operator/values.yaml
  docs/installation.md
Labels: documentation, size/S, helm-chart

#169 Add TF configuration for provisioning TFE test instance
  .github/test-infra/tfe/README.md
  .github/test-infra/tfe/initial-admin/admin.tf
  .github/test-infra/tfe/main.tf
  .github/test-infra/tfe/outputs.tf
  .github/test-infra/tfe/terraform.auto.tfvars
  .github/test-infra/tfe/variables.tf
  .github/test-infra/tfe/versions.tf
  .gitignore
Labels: size/L

#142 📖 Add `How To Release`
  .github/pr-labeler.yml
  .github/workflows/tag-release.yaml
  RELEASING.md
Labels: size/S

#170 🚀 Remove auto apply from Run to inherit it from the Workspace
  CHANGELOG.md
  controllers/module_controller.go
Labels: size/XS, golang, controller, kind:module

#172 🚀 Make the module name configurable
  CHANGELOG.md
  Makefile
  api/v1alpha2/agentpool_types.go
  api/v1alpha2/module_types.go
  api/v1alpha2/workspace_types.go
  charts/terraform-cloud-operator/crds/app.terraform.io_modules.yaml
  config/crd/bases/app.terraform.io_agentpools.yaml
  config/crd/bases/app.terraform.io_modules.yaml
  controllers/agentpool_controller_deployment.go
  controllers/consts.go
  controllers/module_controller_test.go
  controllers/workspace_controller_notifications_test.go
  docs/api-reference.md
  docs/examples/module-moduleName.yaml
  docs/examples/module-variables-and-outputs.yaml
  docs/module.md
Labels: documentation, size/L, crd, helm-chart, api, golang, controller, test, kind:module

#182 🤖 Update `build` workflow
  .github/workflows/build.yml
Labels: size/XS

#177 Bump up GHA hashicorp/actions-docker-build from 1.3.4 to 1.5.0
  .github/workflows/build.yml
Labels: size/XS

#149 🤖 Add Helm chart release automation
  RELEASING.md
  scripts/update-helm-chart.sh
  version/HELM_CHART_VERSION
Labels: documentation, size/M

#185 🌱 Bump up multiple dependencies
  CHANGELOG.md
  charts/terraform-cloud-operator/crds/app.terraform.io_agentpools.yaml
  charts/terraform-cloud-operator/templates/configmap.yaml
  charts/terraform-cloud-operator/templates/deployment.yaml
  config/crd/bases/app.terraform.io_agentpools.yaml
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: crd, helm-chart, golang, size/XL, controller, test
