Repository hashicorp/hcp-terraform-operator, pull requests merged in 2025-08, with the labels that each got.

#617 📖 Customer Resource -> Custom Resource in FAQ
  docs/faq.md
Labels: documentation, size/XS

#629 🐛 Sensitive variables not updated on sensitivity change
  .changes/unreleased/BUG FIXES-629-20250804-183959.yaml
  internal/controller/workspace_controller_variables.go
  internal/controller/workspace_controller_variables_test.go
Labels: size/XS, golang, test, kind:workspace

#618 🐛 Adjust agent scaling algorithm to not include waiting for user interaction statuses
  .changes/unreleased/BUG FIXES-618-20250806-133210.yaml
  internal/controller/agentpool_controller_autoscaling.go
Labels: size/S, golang
